est-ios2-2nd-team-1/1PodShuffle

RandomMusic/RandomMusic.xcodeproj/project.pbxproj, RandomMusic/RandomMusic/Storyboard/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/MainViewController+Actions.swift, RandomMusic/RandomMusic/View/ViewController/MainViewController+UIUpdate.swift, RandomMusic/RandomMusic/View/ViewController/MainViewController.swift
- 메인화면에 좋아요/싫어요 버튼을 추가했습니다.
- 각 버튼들에 대한 `Actions`를 추가하고, 파일을 분리했습니다.
=> ui: 좋아요/싫어요 버튼 추가

RandomMusic/RandomMusic/Etc/Assets.xcassets/MainColor.colorset/Contents.json, RandomMusic/RandomMusic/Storyboard/PlayListView.storyboard, RandomMusic/RandomMusic/View/Cell/SongTableViewCell.swift, RandomMusic/RandomMusic/View/ViewController/PlayListViewController.swift
1. 재생 목록 추가
2. assets 파일에 MainColor 추가
=> ui: 재생목록 화면 추가

RandomMusic/RandomMusic.xcodeproj/project.pbxproj, RandomMusic/RandomMusic/Data/DataManager.swift, RandomMusic/RandomMusic/Model/Song+Extension.swift, RandomMusic/RandomMusic/Model/SongEntity.swift, RandomMusic/RandomMusic/View/ViewController/PlayListViewController.swift
---
- DataManager에 있는 `fetchedResults` 와 플레이리스트 뷰의 tableView와 연결
`let fetchedResults: NSFetchedResultsController<Song>`
`DataManager.shared.fetchedResults.delegate = self`
```swift
extension PlayListViewController: UITableViewDataSource {
func numberOfSections(in tableView: UITableView) -> Int {
return DataManager.shared.fetchedResults.sections?.count ?? 0
}
func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
guard let sections = DataManager.shared.fetchedResults.sections else {
return 0
}
let sectionInfo = sections[section]
return sectionInfo.numberOfObjects
}
func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
let cell = tableView.dequeueReusableCell(withIdentifier: String(describing: SongTableViewCell.self), …
```
=> feat: PlayList 테이블뷰 데이터 연결 및 이미지 가져오는 계산 속성 추가

RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/View/ViewController/MainViewController.swift
=> fix: indent 조정

RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift
<image width="300" src="https://github.com/user-attachments/assets/3875fda0-17c9-468d-955d-4e8f6a77fc2e" />
위 이미지처럼 한곡반복 버튼을 활성화 상태로 두고 곡이 끝까지 재생되면
해당 곡의 처음부터 다시 재생됩니다.
=> feat: 한곡반복 기능 추가

RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift
- 현재 곡이 재생 완료되었을 때, 다음 랜덤곡이 자동으로 재생됩니다.
- `playedSong`이라는 임시 배열에서 fetch된 곡들을 담고 있습니다.
=> feat: 다음곡 자동재생 기능 추가

RandomMusic/RandomMusic/App/SceneDelegate.swift, RandomMusic/RandomMusic/Data/DataManager.swift, RandomMusic/RandomMusic/Data/RandomMusic.xcdatamodeld/RandomMusic.xcdatamodel/contents, RandomMusic/RandomMusic/Info.plist, RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/Manager/RemoteManager.swift, RandomMusic/RandomMusic/Model/SongModel.swift, RandomMusic/gitattributes, gitattributes
---
백그라운드 재생과 이벤트를 담당하는 객체입니다. `MPRemoteCommandCenter` 를 사용합니다.
초기화는 SceneDelegate 단계에서 초기화합니다.
```swift
RemoteManager.shared.configure()
```
오디오 세션의 카테고리와 동작모드를 설정합니다. 해당 작업을 먼저 진행해야 잠금 화면과 백그라운드에서 재생 및 제어가 가능합니다.
```swift
try? AVAudioSession.sharedInstance().setCategory(.playback, mode: .default, options: [])
try? AVAudioSession.sharedInstance().setActive(true)
```
백그라운드에서 제어에 따른 콜백 메소드를 정의합니다.
```swift
commandCenter.playCommand.addTarget { [weak self] _ in
guard let self = self else { return .noActionableNowPlayingItem }
guard let player = playerManager.player else { return .noActionableNowPlayingItem }
switch player.timeControlStatus {
case .paused, .waitingToPlayAtSpecifiedRate:
player.play()
return .success
case .playing:
return .success
default:
return .noActionableNowPlayingItem
} …
```
=> Feat: 백그라운드 재생 및 이벤트 구현 

RandomMusic/RandomMusic/Manager/NetworkManager.swift, RandomMusic/RandomMusic/Manager/PreferenceManager.swift, RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift
- 메인 화면 하단에 있는 재생목록 영역에 현재 곡 정보를 표시하도록 했습니다.
| Before | After | 재생목록 클릭시 |
| -- | -- | -- |
| ![simulator_screenshot_16D0390E-A970-4380-B9A7-09570F9D6C22](https://github.com/user-attachments/assets/359e510a-680d-4e6e-a395-d0c77269fcfd) | ![simulator_screenshot_0013A935-246E-421A-BC0E-728F16E76668](https://github.com/user-attachments/assets/a5ce93dc-4804-4e0d-9f6b-77dd8525cf42) | ![simulator_screenshot_EE173D67-5ABB-4CE9-9D98-B6CF60818E07](https://github.com/user-attachments/assets/aaa5f53e-995b-4a25-b2c4-da029b4206a6) |
=> ui: 메인화면 하단 재생목록 디자인

RandomMusic/RandomMusic/View/ViewController/OnBoarding/OnBoardingViewController.swift
=> feat: 장르 선택에 따른 선호도 데이터 관련 추가

RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard
<image width="300" src="https://github.com/user-attachments/assets/4e50f807-f759-4ce4-9fc7-78ceaad0cd4e">
=> fix: 메인화면 재생목록 제목 짤림 수정

RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/Manager/RemoteManager.swift, RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift, RandomMusic/RandomMusic/View/ViewController/Playlist/PlayListViewController.swift
- 메인화면에서 DB로부터 가져온 플레이리스트를 나타내도록 하였습니다.
- 해당 플레이리스트는 PlayerManager에서 불러오고 수정을 요청합니다.
- 그 과정에서 `moveForward()` 와 관련한 비동기 처리를 추가했습니다.
- 메인화면 상단 타이틀 content priority 수정
=> refactor: PlayerManager DB 데이터 적용 및 구조 개선

RandomMusic/RandomMusic/Data/DataManager.swift, RandomMusic/RandomMusic/Manager/PlayerManager.swift
---
`onSongChanged?()` 추가로 해결했습니다.
=> Fix: 플레이리스트 선택과 메인 화면 동기화 작업

RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard
| Before | After |
| -- | -- |
| ![simulator_screenshot_09FA9164-7295-41A6-9172-DDF22CF7EEAB](https://github.com/user-attachments/assets/26c69e9a-f7d4-4222-9646-556c5026ae8a) | ![simulator_screenshot_378ED116-0D45-432A-A771-8DD797E61A47](https://github.com/user-attachments/assets/9b5a64bb-7877-4f18-a7a1-8835aaa784ee) |
=> ui: 메인화면 디자인 수정

RandomMusic/RandomMusic/Manager/PlayerManager.swift
---
크게 바뀐 코드는 없고 코드 정리를 진행했습니다.
private 메소드가 너무 많아서 구분하기 위해 모두 extension으로 빼뒀습니다.
=> Refactor: PlayerManager 코드 정리

RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift
| 아이폰 세로 | 아이패드 세로 | 아이패드 가로 |
| -- | -- | -- |
| ![simulator_screenshot_7A54D37B-8DE1-49C2-A196-4D849EED962C](https://github.com/user-attachments/assets/9a905e78-8be4-4dee-9d19-ce1973e3ec11) | ![simulator_screenshot_5623A88B-D4E8-4149-B098-B139F9B636C3](https://github.com/user-attachments/assets/b5d523d2-0443-4c66-bb3e-ff3ceab19de2) | ![simulator_screenshot_FB91B8C0-AB77-4FE3-9645-396A7A4993EE](https://github.com/user-attachments/assets/9f82ee56-ac80-4caa-8c5f-91d5c9b52d58) |
=> ui: 메인화면 패드 대응 처리

RandomMusic/RandomMusic/Manager/PlayerManager.swift
fix: 배속 수정3. 일시정지 후 다시재생(resume) 에도 배속적용
=> fix: 배속 수정3. 일시정지 후 다시재생(resume) 에도 배속적용

RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard
| Before | After |
| -- | -- |
| <img width="680" alt="스크린샷 2025-06-13 오후 3 31 56" src="https://github.com/user-attachments/assets/157ef015-dd8c-4219-a192-216f0b408aab" /> | <img width="664" alt="스크린샷 2025-06-13 오후 3 54 03" src="https://github.com/user-attachments/assets/21e2db65-d0e7-4f73-aa3a-b8b7528c796b" /> |
=> fix: 긴 가수명 넘침 문제 수정

RandomMusic/RandomMusic/Util/Throttle.swift
---
- 트레일링 클로저 고려해서 파라미터 순서 변경
=> Refactor: 파라미터 순서 변경

RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/Util/UIViewController+Alert.swift, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift, RandomMusic/RandomMusic/View/ViewController/Playlist/PlayListViewController.swift
첫번째 곡에서 재생시간이 3초미만일 때 이전곡 버튼을 클릭하면 알림이 뜨도록 했습니다.
=> feat: 첫번째 곡 알림 추가

RandomMusic/RandomMusic/Manager/PlayerManager.swift, RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift, RandomMusic/RandomMusic/View/ViewController/Playlist/PlayListViewController.swift
- 변수/함수명 변경
- `removeSong()` 함수 분리
- `loadDuration()` Swift Concurrency 적용
=> refactor: PlayerManager 리팩토링

RandomMusic/RandomMusic/View/ViewController/OnBoarding/OnBoardingViewController.swift, RandomMusic/RandomMusic/View/ViewController/OnBoarding/Onboarding.storyboard
=> ui: 온보딩화면 ui오류 수정

RandomMusic/RandomMusic/View/ViewController/Main/MainViewController.swift
'좋아요'나 '싫어요' 버튼 클릭시,
버튼의 스케일이 1.3배 커졌다가 줄어드는 애니메이션을 추가했습니다.
=> ui: 피드백 애니메이션 추가

RandomMusic/RandomMusic/Util/Toast.swift, RandomMusic/RandomMusic/View/ViewController/Playlist/PlayListViewController.swift
=> Fix: ToastView 지속 시간 변경

RandomMusic/RandomMusic/View/ViewController/Setting/SettingView.storyboard
=> ui: setting ui 레이아웃 수정 중

RandomMusic/RandomMusic/View/ViewController/Main/Base.lproj/Main.storyboard, RandomMusic/RandomMusic/View/ViewController/PlayBar/PlayerBarController.swift, RandomMusic/RandomMusic/View/ViewController/Setting/SettingView.storyboard
=> UI: TabBar 색 변경 및 아이콘 변경

RandomMusic/RandomMusic/View/Cell/GenreCell.swift, RandomMusic/RandomMusic/View/ViewController/OnBoarding/OnBoardingViewController.swift, RandomMusic/RandomMusic/View/ViewController/Setting/SettingViewController.swift
fix: setting 화면 선호도 통계 스택뷰 바로 나오도록 수정
-> self.showGenreStatistics() 추가
doc: genrecell, onboardingview, settingviewcontroller docC 작성
=> fix: 통계화면 바로 나오도록 수정 / doc: docC 작성

RandomMusic/RandomMusic/View/Cell/GenreCell.swift, RandomMusic/RandomMusic/View/ViewController/OnBoarding/OnBoardingViewController.swift, RandomMusic/RandomMusic/View/ViewController/Setting/SettingView.storyboard, RandomMusic/RandomMusic/View/ViewController/Setting/SettingViewController.swift
- onboardingview, genrecell, settingviewcontroller DocC 추가 작성
- ui: setting화면 다크모드 ui변경
=> doc: docC 추가 작성

RandomMusic/RandomMusic/View/ViewController/PlayBar/PlayerBarController.swift
=> Fix: 화면 변경할 때마다 재생바 깜빡이는 버그 수정

RandomMusic/RandomMusic/Enum/Genre.swift, RandomMusic/RandomMusic/View/ViewController/Setting/SettingView.storyboard, RandomMusic/RandomMusic/View/ViewController/Setting/SettingViewController.swift
=> UI: Setting 화면 디자인 수정
